[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = ["--cov=BCSFE_Python"]
testpaths = ["tests"]

[tool.mypi]
mypi_path = "src"